clang-tidy: fix warning on unused member
Resolve the following:

```
../src/version.hpp:146:23: error: private field 'bus' is not used [-Werror,-Wunused-private-field]
  146 |     sdbusplus::bus_t& bus;
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ifadd63dfbd7a0903b6f3cd5a7cb060be51006e5f